server:
  port: 8012   
 
spring:    
  application:
    name: order-service   
      
 
logging:
  level:
    com.self.sprintboot.learning.employee: DEBUG
  
    
eureka:         
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5    
      
     